CLI enhancements
csunibo/raccoglitesi pull request #9
Opened 2023-09-21 14:19 UTC by VaiTon

- Remove dependency on the `log` package.
- Permit passing multiple department codes as program arguments.
- Add a parameter to print all known departments.
- Print a good-looking table when printing departments.

2023-09-21 17:20 UTC, foxyseta requested changes
Sono solo questioni linguistiche per i messaggi a schermo.

2023-09-21 17:20 UTC, foxyseta commented on raccoglitesi.go
> +						"non posso prendere trovare il link alla sua pagina")
Correggere il doppio verbo "prendere trovare".
La congiunzione con virgola (_sentence-splice_) è un errore
in italiano. Magari usare i due punti anziché la virgola
(sì, so che era già così).

2023-09-21 17:20 UTC, foxyseta commented on raccoglitesi.go
> +	fmt.Fprintln(os.Stderr, "Request URL:", r.Request.URL, "failed with response:", r.StatusCode, "\nError:", err)
I messaggi sono in due lingue diverse (sì, so che era già così).
Magari sceglierne una delle due.

2023-09-21 17:20 UTC, foxyseta commented on raccoglitesi.go
> +				fmt.Fprintln(os.Stderr, "La pagina dei dipartimenti è probabilmente cambiata, non posso proseguire")
La congiunzione con virgola (sentence-splice) è un errore
in italiano. Magari usare i due punti anziché la virgola
(sì, so che era già così).

2023-09-21 17:20 UTC, foxyseta commented on raccoglitesi.go
> +	fmt.Println("Questa e' la lista dei dipartimenti da cui pui scegliere:")
Era già così, ma possiamo usare l'accento anziché l'apostrofo se non vogliamo tradurre in inglese.

2023-09-21 17:43 UTC, VaiTon commented
@foxyseta io tradurrei tutto in inglese e basta

2023-09-21 18:46 UTC, foxyseta commented
> @foxyseta io tradurrei tutto in inglese e basta

Va benissimo. Mi raccomando mentre traduci rimuovi quei _sentence splice_ che sarebbero un errore anche in inglese.

2023-09-22 02:01 UTC, foxyseta approved these changes
Si può unire a `main` per me.

2023-09-22 07:38 UTC, merged